server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  server:
    enable-self-preservation: false  # Tắt chế độ tự bảo vệ (cho phép test)
    eviction-interval-timer-in-ms: 5000  # Thời gian kiểm tra service ngắt kết nối
  client:
    register-with-eureka: false  # Không đăng ký chính nó
    fetch-registry: false        # Không fetch registry của chính nó
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost